osx_image: xcode10
language: objective-c
install:
- gem install cocoapods -v 1.3.1 --no-document

before_script:
- cd Example
- pod install

script:
- xcodebuild -workspace Popover.xcworkspace -scheme "PopoverExample" -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 8' build test | xcpretty